### ISSUE TITLE
Single-Click App Support

### ISSUE THREAD

**Issue by bobbyshaw** [Space48/bigcommerce-api-js#12]
This library is currently geared around interacting with the BigCommerce APIs. When looking to use this as part of a single-click app, the install and authentication flow has to be managed separately. This can currently be achieved with https://github.com/getconversio/node-bigcommerce but it would be nice to use a single library for interacting with the BC APIs. 

I was wondering how we might approach adding support for these additional endpoints. 

Based on https://developer.bigcommerce.com/api-docs/partner/getting-started/app-development/single-click-apps/single-click-app-oauth-flow, it would need be able to:

- Send a POST request to oauth2/token get convert a temporary access token into a permanent one. 
- Verify a signed payload

If you have any implementation guidance on how this might be approached, it may be something that I can contribute to.

**Comment by S48-Mo** [comment]
This doesn't look like a feature that should live in this package, rather it makes sense for this to be in a separate package that solves problems for BC single-click apps.
I'll look into it later, but for now I'm closing Issue #12.
