### ISSUE TITLE
Typescript support for V2 orders

### ISSUE THREAD

**Issue by cwilson-S48** [Space48/bigcommerce-api-js#13]
There is typescript autocomplete for the V3 orders endpoint but not for V2 orders. Adding this would allow for more details on orders that aren't in the V3 endpoint

https://developer.bigcommerce.com/api-reference/store-management/orders/orders/getanorder

**Comment by joshdifabio** [comment]
It looks like there are types for that endpoint just as there are for other endpoints. I think the issue you're having might be with [some changes](https://github.com/Space48/bigcommerce-api-js/commit/cedcb5e4436cae7c8772576d49dccd0642e188d3) we made a while ago to allow requests to unknown paths (e.g. private beta endpoints).

The effects of the above change are:
1. No autocomplete on the params for any request
2. If the specified params do not match what is expected, `Promise<unknown>` is the resolved return value of the function

Support for requests to unknown paths probably needs rethinking to avoid these issues.

**Comment by cwilson-S48** [comment]
Apologies, looks like I was using an older version of the package (0.1.5) and so the orders endpoint wasn't in the autocomplete suggestions

![Screenshot 2021-09-09 at 10 35 36](https://user-images.githubusercontent.com/45945751/132662302-4a06a9b5-3200-4817-84c2-65a8fd0776ed.png)
![Screenshot 2021-09-09 at 10 44 18](https://user-images.githubusercontent.com/45945751/132664076-40fe46e3-5f34-43cb-aa23-ba8ba2ae96da.png)

Upgrading to 0.2.5 has resolved the issue
