### ISSUE TITLE
Meta property from all BC responses is missing

### ISSUE THREAD

**Issue by gbogdanovski** [Space48/bigcommerce-api-js#16]
https://developer.bigcommerce.com/api-reference/store-management/catalog/products/getproducts
This endpoint returns 2 objects, one is data and the second one is meta.
Your implementation does not return the meta object.

I also noticed that meta is missing on catalog/summary endpoint so i guess it is missing everywhere.

**Comment by S48-Mo** [comment]
@gbogdanovski If you want the `meta` property then you can use a lower-level method called `.send` which will return the raw response.

At the moment we don't have a feature to expose the `meta` property from the response when using the `.get` or `.list` methods. It might be an additional feature later.

The common use-case for the `meta` property is to implement pagination. If that's the case, then the `.list` method will auto-paginate all results for you. If you want to pass a specific `page` and `limit` then the `.get` method can be called with those passed in as query params.
